services:
  sql_composer:
    build:
      dockerfile: Dockerfile
      context: .docker/composer
    image: compono-kit-sql-php
    container_name: sql_composer
    restart: "no"
    working_dir: /app
    volumes:
      - ./:/app

  sql_php:
    image: compono-kit-sql-php
    container_name: sql_php
    restart: "no"
    working_dir: /app
    entrypoint: ["php"]
    depends_on:
      - sql_mariadb
    volumes:
      - ./:/app

  sql_mariadb:
    image: mariadb:11.7
    container_name: sql_mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
